### ISSUE TITLE
Error sending notification

### ISSUE THREAD

**Issue by bogdancondorachi** [youngcut/kirby-form-blocks#11]
I'm getting the following error when I'm submitting the form.

"Error sending notification: Call to a member function value() on null"

It worked well for some days then it started getting this error. I've tried a clean reinstall of the plugin but with the same result.. any idea?

**Comment by BogdanCondorachi** [comment]
Texnixe looked into the code and told that the error seems to be an issue in the $form->parseString()` method of the plugin.

**Comment by youngcut** [comment]
Hi Gobdan

Give me a few days to care about that. In the meanwhile you can try to put this method in a condition.
If you have a solution and you where familiar with git, don't hesitate to make a Pull Request.

Did you post this issue in the Firby-Forum too? May you could post the link of the thread in this conversation?

**Comment by BogdanCondorachi** [comment]
Thanks for the quick replay.

Unfortunately, I don't have the deeper skill to know how to solve this. What's weird is that I had it working just fine for about 2 weeks and suddenly broke. It's working fine if I recreate the block and keep the preset fields but once I delete them and add a new field, the error appears. Also did tests on local or other servers and the error keeps showing. Don't know what could cause this and why it worked for some time before this.

Yes, I've posted it on the forum so maybe someone had an idea what's about and Sonja came up with that answer. Here's the thread if you wanna look into it. [](https://forum.getkirby.com/t/forms-blocks-plugin-error-on-submit/24440)

It's not urgent, I know you have other priorities at the moment but when you got some spare time maybe you could look into it. Thanks again! :)

**Comment by BogdanCondorachi** [comment]
So I had to focus on something else for few days so I've leave it as that. Today I got back at it (still getting the error) so I deleted the form and recreated again (I did that many times before with no result) and this time worked. Everything works fine now, idk why but it works. Still can't figure out the reason for it but hope it will stay that way. I'll keep you noted in case I'm getting the error back.

Thanks again for your responses :)

**Comment by renestalder** [comment]
So, I created two forms and have the issue with both of the forms. The issue also persists when uploaded to a remote server. I currently try to narrow it down to understand where the issue is happening

**Comment by renestalder** [comment]
It looks like the error happens because the code in the sendNotification and sendConfirmation functions assumes there is a field with the name 'email'. So as soon as you remove that field, the issue appears. When you add the field again, the issue is gone.

Because when the field is missing, the parseString function throws the error as there is basically no null check. The only thing this function does is to check whether the value is a string, and in the case it isn't it tries to get the value via `$value->value()` which then fails, because `$value$` can be null.

I think I might be able to send a pull request for that by adding the additional null check. But I believe you might have to rethink that logic with the static programmed email field. I'm not sure that's what you wanted.

**Comment by renestalder** [comment]
Created a pull request, but please make a code review and test it. I'm by no means a PHP developer.
