### ISSUE TITLE
File Upload Field (aka Attachment)

### ISSUE THREAD

**Issue by teichsta** [youngcut/kirby-form-blocks#18]
Hi @youngcut,

thanks for sharing this great plugin. I am wondering how much effort it would be to add a new file field. On our sites we offer our users (children) to send in their articles as a file (foto, audio, video) which we then add to the respective news section.

Thanks in advance, Thomas E.-E.

**Comment by youngcut** [comment]
This could be done with an [custom field type](https://github.com/youngcut/kirby-form-blocks#form-field-types). Check with `$form->isSuccess()` if the form is filled correctly and then upload the file(s). This is what i can offer without extending the plugin.
Otherwise it will take approx one day of work. Maybe with a donation i can implement such form field type in the plugin. 😉

**Comment by youngcut** [comment]
**Kirby Form Blocks 3.0-Beta now available!** This includes your requested Fileupload feature!
[Get the Betaversion now!](https://github.com/youngcut/kirby-form-block-suite/releases/tag/v3.0-BETAorm-block-suite/releases/tag/v3.0-BETA)
